-- Level 2: Intermediate

-- Skills Covered: JOIN, GROUP BY, HAVING, SUM, AVG, MIN, MAX

-- 16. Calculate the total revenue generated by the bookstore.
SELECT 
    SUM(Total_Amount) AS Total_Revenue
FROM Orders;
-- 17. Find the total number of books sold.
SELECT 
    SUM(Quantity) AS Total_Books_Sold
FROM Orders;
-- 18. Calculate the average price of books.
SELECT 
    ROUND(AVG(Price), 2) AS Average_Book_Price
FROM Books;
-- 19. Find the average order value.
SELECT 
    ROUND(AVG(Total_Amount), 2) AS Average_Order_Value
FROM Orders;
-- 20. Display the total number of books available in each genre.
SELECT 
    Genre,
    COUNT(*) AS Number_of_Books
FROM Books
GROUP BY Genre
ORDER BY Number_of_Books DESC;
-- 21. Find the top 5 best-selling books based on quantity sold.
SELECT 
    b.Book_ID,
    b.Title,
    SUM(o.Quantity) AS Total_Quantity_Sold
FROM Orders o
JOIN Books b
    ON o.Book_ID = b.Book_ID
GROUP BY 
    b.Book_ID,
    b.Title
ORDER BY Total_Quantity_Sold DESC
LIMIT 5;
-- 22. Find the bottom 5 least-selling books.
SELECT 
    b.Book_ID,
    b.Title,
    SUM(o.Quantity) AS Total_Quantity_Sold
FROM Orders o
JOIN Books b
    ON o.Book_ID = b.Book_ID
GROUP BY 
    b.Book_ID,
    b.Title
ORDER BY Total_Quantity_Sold ASC
LIMIT 5;
-- 23. Display each customers name along with the books they purchased.
SELECT 
    c.Customer_ID,
    c.Name AS Customer_Name,
    b.Title AS Book_Title,
    o.Order_Date,
    o.Quantity,
    o.Total_Amount
FROM Orders o
JOIN Customers c
    ON o.Customer_ID = c.Customer_ID
JOIN Books b
    ON o.Book_ID = b.Book_ID
ORDER BY o.Order_Date;
-- 24. Calculate the total amount spent by each customer.
SELECT 
    c.Customer_ID,
    c.Name AS Customer_Name,
    SUM(o.Total_Amount) AS Total_Spending
FROM Orders o
JOIN Customers c
    ON o.Customer_ID = c.Customer_ID
GROUP BY 
    c.Customer_ID,
    c.Name
ORDER BY Total_Spending DESC;
-- 25. Find customers who have placed more than one order.
SELECT 
    c.Customer_ID,
    c.Name AS Customer_Name,
    COUNT(o.Order_ID) AS Number_of_Orders
FROM Customers c
JOIN Orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY 
    c.Customer_ID,
    c.Name
HAVING COUNT(o.Order_ID) > 1
ORDER BY Number_of_Orders DESC;
-- 26. Find books that have never been ordered.
SELECT 
    b.Book_ID,
    b.Title,
    b.Genre,
    b.Stock
FROM Books b
LEFT JOIN Orders o
    ON b.Book_ID = o.Book_ID
WHERE o.Book_ID IS NULL;
-- 27. Find the total revenue generated by each genre.
SELECT 
    b.Genre,
    SUM(o.Total_Amount) AS Total_Revenue
FROM Orders o
JOIN Books b
    ON o.Book_ID = b.Book_ID
GROUP BY b.Genre
ORDER BY Total_Revenue DESC;
-- 28. Display monthly sales revenue.
SELECT 
DATE_FORMAT(Order_Date, '%Y-%m') AS Sales_Month, 
SUM(Total_Amount) AS Monthly_Revenue 
FROM Orders 
GROUP BY DATE_FORMAT(Order_Date, '%Y-%m') 
ORDER BY Sales_Month;
-- 29. Find the city with the highest number of customers.
SELECT 
    City,
    COUNT(*) AS Number_of_Customers
FROM Customers
GROUP BY City
ORDER BY Number_of_Customers DESC
LIMIT 1;
-- 30. Find the author whose books generated the highest revenue.
SELECT 
    b.Author,
    SUM(o.Total_Amount) AS Total_Revenue
FROM Orders o
JOIN Books b
    ON o.Book_ID = b.Book_ID
GROUP BY b.Author
ORDER BY Total_Revenue DESC
LIMIT 1;
